import Head from 'next/head'

const HomePage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Strona główna</p>
    </div>
  )
}

export default HomePage;
